name: cpea
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  freezed_annotation:
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  go_router: ^3.0.0
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  flutterfire_ui: ^0.3.0
  dartz: ^0.10.1
  firebase_core: ^1.10.6
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.1.3

  gbx_core:
    path: packages/gbx_core
  gbx_firebase:
    path: packages/gbx_firebase
  gbx_login:
    path: packages/gbx_login
  gbx_firebase_login:
    path: packages/gbx_firebase_login
  google_fonts: ^2.2.0
  salomon_bottom_bar: ^3.2.0
  logger: ^1.1.0
  scroll_snap_list: ^0.8.4
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner:
  freezed:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
